# jobs:
#     main:
#         template: adong/alan-sd-template
#         image: stable-image

shared:
  image: node:18
jobs:
  main:
      requires: [ ~commit ]
      steps:
        - hello: |
           echo hi
