# jobs:
#     main:
#         template: adong/alan-sd-template
#         image: stable-image

# shared:
#   image: node:20
# jobs:
#   main:
#       requires: [ ~commit ]
#       steps:
#         - hello: |
#            echo hi

shared:
    image: node:20
jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - install: npm install screwdriver-template-main
            - validate: ./node_modules/.bin/template-validate
    publish:
        requires: [main]
        steps:
            - install: npm install screwdriver-template-main
            - publish: ./node_modules/.bin/template-publish
            - autotag: ./node_modules/.bin/template-tag --name adong/alan-sd-template --tag latest
            - tag: ./node_modules/.bin/template-tag --name adong/alan-sd-template --tag stable
    remove:
        steps:
            - install: npm install screwdriver-template-main
            - remove: ./node_modules/.bin/template-remove --name adong/alan-sd-template
    remove_tag:
        steps:
            - install: npm install screwdriver-template-main
            - remove_tag: ./node_modules/.bin/template-remove-tag --name adong/alan-sd-template --tag stable
